site_name: Zeta
repo_url: https://github.com/bilacchi/zeta/
repo_name: bilacchi/zeta
edit_uri: tree/main/docs

theme:
  name: material
  logo: assets/logo-w.png
  favicon: assets/logo.ico
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.footer
  custom_dir: docs/overrides

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.tasklist
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - stylesheets/extra.css

watch:
  - zeta
  - zeta/colormap
  - zeta/plot

plugins:
- macros
- mkdocstrings:
    handlers:
      python:
        options:
          show_symbol_type_heading: true
          separate_signature: true
          show_signature_annotations: true
        paths: [zeta]

extra:
  commands:
    run: poetry run zeta