name: Pipeline
on:
  push

permissions:
  contents: write

jobs:
  install:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ['3.11', '3.12']
        os: [ubuntu-latest] #, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Installing Poetry
        run: pip install -U poetry
        
      - name: Installing project dependencies
        run: poetry install --only main #--without doc
  
  docs:
    name: Build Docs
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.11'
          cache: 'pip'

      - name: Installing Poetry
        run: pip install -U poetry

      - name: Installing project dependencies
        run: poetry install

      - name: Deploy Github Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: poetry run mkdocs gh-deploy --force

  pypi:
    name: Release To PyPi
    needs: [install, docs]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.11'
          cache: 'pip'

      - name: Installing Poetry
        run: pip install -U poetry

      - name: Install publishing dependencies
        run: poetry install --only main

      - name: Build and publish
        run: poetry build

      - name: Publish
        run: |
          poetry config http-basic.pypi __token__ ${{ secrets.PYPI_TOKEN }}
          poetry publish 